// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoaogbk-NMa9lAHQojH7rJby3jJx-4dck',
    appId: '1:106137562514:web:e2783717e16c2c7335e54b',
    messagingSenderId: '106137562514',
    projectId: 'travel-super-app-a47cb',
    authDomain: 'travel-super-app-a47cb.firebaseapp.com',
    storageBucket: 'travel-super-app-a47cb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDd1BBxCl-MZUyAJqtASJb5Zbq_ZCx4-w4',
    appId: '1:106137562514:android:ea4282dc669a7d3335e54b',
    messagingSenderId: '106137562514',
    projectId: 'travel-super-app-a47cb',
    storageBucket: 'travel-super-app-a47cb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDu5qr_04lLIB3iyaxA2I_5MW_V4vTDqxI',
    appId: '1:106137562514:ios:f9f82b410b533cd535e54b',
    messagingSenderId: '106137562514',
    projectId: 'travel-super-app-a47cb',
    storageBucket: 'travel-super-app-a47cb.firebasestorage.app',
    iosBundleId: 'com.itarevo.app',
  );
}
